# Replace these with your actual API keys
POLYGON_API_KEY = "r65B9O5aplSJn7BWSo8z8pNH8v2wW5yc"
ALPHA_VANTAGE_API_KEY = "your_alpha_vantage_api_key_here"

# Add any other sensitive configuration here
# For example:
# DATABASE_URL = "your_database_url_here"
# OTHER_API_KEY = "your_other_api_key_here"
